In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import os

### 2026

In [51]:
df26 = pd.read_csv('bikeshare-ridership-2026.csv')

In [52]:
df26.info()

<class 'pandas.DataFrame'>
RangeIndex: 6830174 entries, 0 to 6830173
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    int64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [23]:
df26.isna().sum()

Trip_Id                   0
Trip_Duration             0
Start_Station_Id          0
Start_Time                0
Start_Station_Name        0
End_Station_Id        12951
End_Time               8065
End_Station_Name      12951
Bike_Id                   0
User_Type                 0
Bike_Model                0
dtype: int64

In [53]:
df26.columns = [c.lower().replace(' ', '_') for c in df26.columns]

In [54]:
df26.info()

<class 'pandas.DataFrame'>
RangeIndex: 6830174 entries, 0 to 6830173
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             int64
 1   trip_duration       int64
 2   start_station_id    int64
 3   start_time          str
 4   start_station_name  str
 5   end_station_id      float64
 6   end_time            str
 7   end_station_name    str
 8   bike_id             int64
 9   user_type           str
 10  bike_model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [55]:
before_mem = df26.memory_usage(deep=True).sum() / 1e9
before_mem

np.float64(1.292371177)

In [56]:
df26['start_time'] = pd.to_datetime(df26['start_time'])
df26['end_time'] = pd.to_datetime(df26['end_time'])

In [57]:
before_mem = df26.memory_usage(deep=True).sum() / 1e9
before_mem

np.float64(1.032124028)

In [58]:
df26.bike_model.nunique()
df26.bike_model.unique()

<ArrowStringArray>
['ICONIC', 'EFIT', 'ASTRO']
Length: 3, dtype: str

In [ ]:
# bike_model_map = {'ICONIC': 0, 'EFIT': 1, 'ASTRO': 2, 'Unknown': -1}
# df26['bike_model'] = df26['bike_model'].map(bike_model_map)

In [ ]:
# before_mem = df26.memory_usage(deep=True).sum() / 1e9
# before_mem

np.float64(0.99411018)

In [ ]:
# df26.user_type.nunique()
# df26.user_type.unique()

<ArrowStringArray>
['Member', 'Casual']
Length: 2, dtype: str

In [ ]:
# user_type_map = {'Member': 0, 'Casual': 1}
# df26['user_type'] = df26['user_type'].map(user_type_map)

In [ ]:
# before_mem = df26.memory_usage(deep=True).sum() / 1e9
# before_mem

np.float64(0.953129136)

In [59]:
df26['user_type'] = df26['user_type'].astype('category')
df26['bike_model'] = df26['bike_model'].astype('category')

In [60]:
# categorizing station_name columns
df26['start_station_name'] = df26['start_station_name'].astype('category')
df26['end_station_name'] = df26['end_station_name'].astype('category')
df26.memory_usage(deep=True).sum() / 1e9

np.float64(0.423546272)

In [61]:
# downcasting numeric columns
int_cols = df26.select_dtypes(include='int64').columns
df26[int_cols] = df26[int_cols].apply(pd.to_numeric, downcast='integer')

float_cols = df26.select_dtypes(include='float64').columns
df26[float_cols] = df26[float_cols].apply(pd.to_numeric, downcast='float')
df26.memory_usage(deep=True).sum() / 1e9

np.float64(0.259622096)

In [ ]:
#result - from 1.292371177 GB to 0.259622096 GB

In [ ]:
#put all steps into function 
def optimize_df(df):
    df['start_time'] = pd.to_datetime(df['start_time'])
    df['end_time'] = pd.to_datetime(df['end_time'])
    df['bike_model'] = df['bike_model'].astype('category')
    df['user_type'] = df['user_type'].astype('category')
    df['start_station_name'] = df['start_station_name'].astype('category')
    df['end_station_name'] = df['end_station_name'].astype('category')
    int_cols = df.select_dtypes(include='int64').columns
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
    float_cols = df.select_dtypes(include='float64').columns
    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
    return df

### 2025

In [63]:
os.listdir('bikeshare-ridership-2025')

['bikeshare_2025_10.csv',
 'bikeshare_2025_04.csv',
 'bikeshare_2025_05.csv',
 'bikeshare_2025_11.csv',
 'bikeshare_2025_07.csv',
 'bikeshare_2025_12.csv',
 'bikeshare_2025_06.csv',
 'bikeshare_2025_02.csv',
 'bikeshare_2025_03.csv',
 'bikeshare_2025_01.csv',
 'bikeshare_2025_08.csv',
 'bikeshare_2025_09.csv']

In [44]:
files25 = os.listdir('bikeshare-ridership-2025')

monthly_dfs_25 = [
   pd.read_csv(os.path.join('bikeshare-ridership-2025', f), encoding='cp1252') for f in files25
]

In [67]:
df25 = pd.concat(monthly_dfs_25, ignore_index=True)
df25.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,41865752,347,7389.0,2025-10-01 00:01:03,College Park - Gerrard Entrance,7693.0,2025-10-01 00:06:50,College Park - Gerrard Entrance,5579,Member,ICONIC
1,41865762,806,7485.0,2025-10-01 00:02:49,Blythwood Rd / Yonge St - SMART,7676.0,2025-10-01 00:16:15,Blythwood Rd / Yonge St - SMART,6681,Casual,EFIT
2,41865748,321,7030.0,2025-10-01 00:00:32,Bay St / Wellesley St W,7058.0,2025-10-01 00:05:53,Bay St / Wellesley St W,1392,Casual,ICONIC
3,41865749,125,7386.0,2025-10-01 00:00:48,D'Arcy St / McCaul St - SMART,7257.0,2025-10-01 00:02:53,D'Arcy St / McCaul St - SMART,2545,Member,ICONIC
4,41865767,782,7894.0,2025-10-01 00:03:23,Millwood Rd / Southvale Dr,7194.0,2025-10-01 00:16:25,Millwood Rd / Southvale Dr,9947,Member,EFIT

In [46]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 7812520 entries, 0 to 7812519
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    float64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(2), int64(3), str(6)
memory usage: 1.4 GB

In [68]:
df25.columns = [c.lower().replace(' ', '_') for c in df25.columns]
df25.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [69]:
df25.memory_usage(deep=True).sum() / 1e9

np.float64(1.484543626)

In [70]:
df25 = optimize_df(df25)

df25.memory_usage(deep=True).sum()/ 1e9

np.float64(0.31257724)

In [ ]:
#from 1.484543626 GB to  0.31257724 GB for 2025

In [50]:
df25.head()

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model
0,41865752,347,7389.0,2025-10-01 00:01:03,College Park - Gerrard Entrance,7693.0,2025-10-01 00:06:50,College Park - Gerrard Entrance,5579,0,0.0
1,41865762,806,7485.0,2025-10-01 00:02:49,Blythwood Rd / Yonge St - SMART,7676.0,2025-10-01 00:16:15,Blythwood Rd / Yonge St - SMART,6681,1,1.0
2,41865748,321,7030.0,2025-10-01 00:00:32,Bay St / Wellesley St W,7058.0,2025-10-01 00:05:53,Bay St / Wellesley St W,1392,1,0.0
3,41865749,125,7386.0,2025-10-01 00:00:48,D'Arcy St / McCaul St - SMART,7257.0,2025-10-01 00:02:53,D'Arcy St / McCaul St - SMART,2545,0,0.0
4,41865767,782,7894.0,2025-10-01 00:03:23,Millwood Rd / Southvale Dr,7194.0,2025-10-01 00:16:25,Millwood Rd / Southvale Dr,9947,0,1.0

### 2024

In [73]:
df24 = pd.read_csv('bikeshare-ridership-2024.csv')

In [12]:
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 6953094 entries, 0 to 6953093
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    int64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [13]:
df24.isna().sum()

Trip_Id                  0
Trip_Duration            0
Start_Station_Id         0
Start_Time               0
Start_Station_Name       0
End_Station_Id        8424
End_Time              5822
End_Station_Name      8424
Bike_Id                  0
User_Type                0
Bike_Model               0
dtype: int64

In [74]:
df24.columns = [c.lower().replace(' ', '_') for c in df24.columns]
df24.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [76]:
df24.memory_usage(deep=True).sum() / 1e9

np.float64(1.324427269)

In [77]:
df24 = optimize_df(df24)
df24.memory_usage(deep=True).sum() / 1e9

np.float64(0.264278176)

In [ ]:
# 1.324427269 -> 0.264278176 GB

In [83]:
del monthly_dfs_25
import gc; gc.collect()

2580

### 2021 - 2023

In [100]:
folders21_23  = [l for l in os.listdir() if '2021' in l or '2022' in l or '2023' in l]
folders21_23

['bikeshare-ridership-2023',
 'bikeshare-ridership-2022',
 'bikeshare-ridership-2021']

In [101]:
months = [f"0{i}" if i< 10 else f"{i}" for i in range(1, 13)]

In [102]:
def month_path(folder, month):
    p = f"{folder}/Bike share ridership {folder[-4:]}-{month}"
    return f"{p}.csv" if os.path.exists(f"{p}.csv") else f"{p}.zip"

months = [f"0{i}" if i < 10 else f"{i}" for i in range(1, 13)]
monthly_dfs = [
    pd.read_csv(month_path(folder, month), encoding='cp1252')
    for folder in folders21_23
    for month in months
]
df21_23 = pd.concat(monthly_dfs, ignore_index=True)
df21_23.shape

(13908792, 11)

In [103]:
df21_23['Trip Id'] = df21_23['Trip Id'].combine_first(df21_23['ï»¿Trip Id'])

In [104]:
df21_23.drop('ï»¿Trip Id', axis = 1, inplace=True)

In [105]:
df21_23.columns = [c.lower().replace(' ', '_') for c in df21_23.columns]

cols = [col for col in df21_23.columns if col != 'trip_id']
df21_23 = df21_23[['trip_id'] + cols]
df21_23.head()

,trip_id,trip__duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type
0,20148784.0,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770.0,Casual Member
1,20148785.0,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400.0,Casual Member
2,20148786.0,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068.0,Annual Member
3,20148790.0,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427.0,Casual Member
4,20148791.0,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840.0,Casual Member

In [91]:
df21_23.info()

<class 'pandas.DataFrame'>
RangeIndex: 13908792 entries, 0 to 13908791
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             float64
 1   trip__duration      int64
 2   start_station_id    int64
 3   start_time          str
 4   start_station_name  str
 5   end_station_id      float64
 6   end_time            str
 7   end_station_name    str
 8   bike_id             float64
 9   user_type           str
dtypes: float64(3), int64(2), str(5)
memory usage: 2.3 GB

In [106]:
df21_23.columns = [c.replace('__', '_') for c in df21_23.columns]
df21_23.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [107]:
#put all steps into function 
def optimize_df(df):
    df['start_time'] = pd.to_datetime(df['start_time'])
    df['end_time'] = pd.to_datetime(df['end_time'])
    # df['bike_model'] = df['bike_model'].astype('category')
    df['user_type'] = df['user_type'].astype('category')
    df['start_station_name'] = df['start_station_name'].astype('category')
    df['end_station_name'] = df['end_station_name'].astype('category')
    int_cols = df.select_dtypes(include='int64').columns
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
    float_cols = df.select_dtypes(include='float64').columns
    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
    return df

In [108]:
df21_23.memory_usage(deep=True).sum()/1e9

np.float64(2.446753743)

In [109]:
df21_23 = optimize_df(df21_23)
df21_23.memory_usage(deep=True).sum()/1e9

np.float64(0.598131214)

In [ ]:
# from 2.446753743 to 0.598131214 GB
# del df21_23

### 2020

In [232]:
monthly_dfs_20 = [
    pd.read_csv(os.path.join('bikeshare-ridership-2020', file)) for file in os.listdir('bikeshare-ridership-2020')
]

In [133]:
os.listdir('bikeshare-ridership-2020')

['2020-02.csv',
 '2020-03.csv',
 '2020-01.csv',
 '2020-10.csv',
 '2020-04.csv',
 '2020-05.csv',
 '2020-11.csv',
 '2020-07.csv',
 '2020-12.csv',
 '2020-06.csv',
 '2020-08.csv',
 '2020-09.csv']

In [247]:
# connandrum with 2020-10
# problem with 2020-10.csv, 249 rows are missing the Trip Duration field entirely, 
# which shifts every subsequent column one position to the left for those rows. 
df20_10 = pd.read_csv(os.path.join('bikeshare-ridership-2020/2020-10.csv'))

In [248]:
df20_10 = df20_10.astype('object')

In [249]:
cols = df20_10.columns.tolist()

In [252]:
bad_rows = pd.to_numeric(df20_10[cols[2]], errors='coerce').isna() & df20_10[cols[2]].notna()

# df20_10.loc[bad_rows, cols[2:]].dtypes
df20_10.loc[bad_rows, cols[2:]] = df20_10.loc[bad_rows, cols[1:-1]].values
# df20_10.loc[bad_rows, cols[1]] = np.nan

In [253]:
df20_10.loc[bad_rows, cols[1]] = np.nan

In [239]:
monthly_dfs_20 = [
    pd.read_csv(os.path.join('bikeshare-ridership-2020', file)) for file in os.listdir('bikeshare-ridership-2020') if file !='2020-10.csv'
]

In [ ]:
# monthly_dfs_20 = []

# for file in os.listdir('bikeshare-ridership-2020'):
    
#     tmp_df = pd.read_csv(os.path.join('bikeshare-ridership-2020', file))
#     num_cols = tmp_df.columns[tmp_df.dtypes=='int64']
#     tmp_df[num_cols] = [pd.to_numeric(col, errors='coerce') for col in num_cols]
    
#     monthly_dfs_20.append(tmp_df)

In [208]:
monthly_dfs_20.append(df20_10)

In [240]:
df20 = pd.concat(monthly_dfs_20, ignore_index=True)
df20.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,7452736,625,7162,02/01/2020 00:00,Hayter St / Laplante Ave,7190.0,02/01/2020 00:11,St. George St / Hoskin Ave,653.0,Annual Member
1,7452737,426,7170,02/01/2020 00:01,Spadina Ave / Willcocks St,7239.0,02/01/2020 00:08,Bloor St W / Manning Ave - SMART,4682.0,Annual Member
2,7452738,817,7475,02/01/2020 00:03,Jarvis St / Richmond St E,7075.0,02/01/2020 00:16,Queens Quay W / Dan Leckie Way,3852.0,Annual Member
3,7452739,653,7099,02/01/2020 00:03,Cherry St / Mill St,7292.0,02/01/2020 00:14,Granby St / Church St - SMART,4546.0,Annual Member
4,7452740,189,7176,02/01/2020 00:03,Bathurst St / Fort York Blvd,7402.0,02/01/2020 00:06,Wellington St W / Bathurst St,4867.0,Annual Member

In [241]:
df20.columns = [c.lower().replace(' ', '_') for c in df20.columns]
df20.columns = [c.lower().replace('__', '_') for c in df20.columns]
df20.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [195]:
df26.columns.difference(df20.columns)

Index(['bike_model'], dtype='str')

In [119]:
import numpy as np

In [196]:
sample_idx = np.random.choice(df20.shape[0], 15)
print(df20['start_time'].iloc[sample_idx].tolist())

['08/14/2020 17:46', '07/10/2020 19:51', '10/04/2020 11:58', '11/01/2020 07:55', '07/25/2020 16:52', '09/25/2020 16:53', '07/21/2020 23:41', '11/13/2020 14:29', '09/05/2020 18:03', '07/01/2020 13:05', '10/10/2020 19:58', '09/25/2020 19:27', '09/13/2020 15:41', '06/19/2020 09:34', '12/18/2020 19:08']

In [242]:
pd.to_datetime(df20['start_time'])

0         2020-02-01 00:00:00
1         2020-02-01 00:01:00
2         2020-02-01 00:03:00
3         2020-02-01 00:03:00
4         2020-02-01 00:03:00
                  ...
2633464   2020-09-30 23:59:00
2633465   2020-09-30 23:59:00
2633466   2020-09-30 23:59:00
2633467   2020-09-30 23:59:00
2633468   2020-09-30 23:59:00
Name: start_time, Length: 2633469, dtype: datetime64[us]

In [243]:
df20 = optimize_df(df20)

In [254]:
df20_10.columns = [c.lower().replace(' ', '_') for c in df20_10.columns]
df20_10.columns = [c.lower().replace('__', '_') for c in df20_10.columns]
df20_10.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [255]:
pd.to_datetime(df20_10['start_time'])

0        2020-10-01 00:00:00
1        2020-10-01 00:00:00
2        2020-10-01 00:01:00
3        2020-10-01 00:01:00
4        2020-10-01 00:01:00
                 ...
277834   2020-10-31 23:57:00
277835   2020-10-31 23:57:00
277836   2020-10-31 23:58:00
277837   2020-10-31 23:59:00
277838   2020-10-31 23:59:00
Name: start_time, Length: 277839, dtype: datetime64[us]

In [ ]:
df20_10 = optimize_df(df20_10)

In [257]:
df20 = pd.concat([df20, df20_10], ignore_index=True)

In [258]:
df20.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [260]:
df20 = df20.sort_values('start_time')

### 2019

In [261]:
quaterly_dfs_19 = [
    
     pd.read_csv(os.path.join('bikeshare-ridership-2019', file)) for file in os.listdir('bikeshare-ridership-2019')

]

In [262]:
df19 = pd.concat(quaterly_dfs_19, ignore_index=True)
df19.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,5533843,1834.0,7352,07/01/2019 00:00,Cosburn Ave / Donlands Ave,7352.0,07/01/2019 00:30,Cosburn Ave / Donlands Ave,989,Casual Member
1,5533844,338.0,7016,07/01/2019 00:00,Bay St / Queens Quay W (Ferry Terminal),7068.0,07/01/2019 00:06,Dockside Dr / Queens Quay E (Sugar Beach),4006,Annual Member
2,5533845,1433.0,7193,07/01/2019 00:00,Queen St W / Gladstone Ave,7285.0,07/01/2019 00:24,Spadina Ave / Harbord St - SMART,1512,Casual Member
3,5533846,1042.0,7369,07/01/2019 00:00,Dupont St / Emerson Ave SMART,7239.0,07/01/2019 00:18,Bloor St W / Manning Ave - SMART,3219,Casual Member
4,5533847,4203.0,7168,07/01/2019 00:01,Queens Quay / Yonge St,7226.0,07/01/2019 01:11,Lake Shore Blvd W / The Boulevard Club,4425,Casual Member

In [28]:
df19.info()

<class 'pandas.DataFrame'>
RangeIndex: 2439517 entries, 0 to 2439516
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip Id             int64
 1   Trip  Duration      float64
 2   Start Station Id    int64
 3   Start Time          str
 4   Start Station Name  str
 5   End Station Id      float64
 6   End Time            str
 7   End Station Name    str
 8   Bike Id             int64
 9   User Type           str
dtypes: float64(2), int64(3), str(5)
memory usage: 418.5 MB

In [263]:
df19.columns = [c.lower().replace(' ', '_') for c in df19.columns]
df19.columns

Index(['trip_id', 'trip__duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [264]:
df19 = optimize_df(df19)

### 2018

In [265]:
quaterly_dfs_18 = [
     pd.read_csv(os.path.join('bikeshare2018', file)) for file in os.listdir('bikeshare2018')
]

In [31]:
df18 = pd.concat(quaterly_dfs_18, ignore_index=True)
df18.head()

,trip_id,trip_duration_seconds,from_station_id,trip_start_time,from_station_name,trip_stop_time,to_station_id,to_station_name,user_type
0,3244396,528,7254,7/1/2018 0:00,Borden St / Bloor St W - SMART,7/1/2018 0:08,7140,Macpherson Ave / Spadina Rd,Annual Member
1,3244398,570,7031,7/1/2018 0:00,Jarvis St / Isabella St,7/1/2018 0:09,7167,Queen St E / George St (Moss Park),Annual Member
2,3244397,368,7286,7/1/2018 0:00,Gerrard St E / Broadview - SMART,7/1/2018 0:06,7286,Gerrard St E / Broadview - SMART,Casual Member
3,3244399,1147,7248,7/1/2018 0:00,Baldwin Ave / Spadina Ave - SMART,7/1/2018 0:19,7020,Phoebe St / Spadina Ave,Annual Member
4,3244400,730,7207,7/1/2018 0:02,Dundas St W / Crawford St,7/1/2018 0:14,7000,Fort York Blvd / Capreol Ct,Annual Member

In [32]:
df18.info()

<class 'pandas.DataFrame'>
RangeIndex: 1922955 entries, 0 to 1922954
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trip_id                int64
 1   trip_duration_seconds  int64
 2   from_station_id        int64
 3   trip_start_time        str
 4   from_station_name      str
 5   trip_stop_time         str
 6   to_station_id          int64
 7   to_station_name        str
 8   user_type              str
dtypes: int64(4), str(5)
memory usage: 309.0 MB

In [33]:
df18.columns = [c.lower().replace(' ', '_') for c in df18.columns]
df18.columns

Index(['trip_id', 'trip_duration_seconds', 'from_station_id',
       'trip_start_time', 'from_station_name', 'trip_stop_time',
       'to_station_id', 'to_station_name', 'user_type'],
      dtype='str')

### 2017

In [34]:
quaterly_dfs_17 = [
    
     pd.read_csv(os.path.join('2017 Data', file)) for file in os.listdir('2017 Data')

]

In [35]:
df17 = pd.concat(quaterly_dfs_17, ignore_index=True)
df17.head()

,trip_id,trip_start_time,trip_stop_time,trip_duration_seconds,from_station_id,from_station_name,to_station_id,to_station_name,user_type
0,868665,1/4/2017 0:01,1/4/2017 0:06,297,7073.0,Bremner Blvd / Spadina Ave,7211.0,Fort York Blvd / Garrison Rd,Member
1,868666,1/4/2017 0:07,1/4/2017 0:11,236,7038.0,Dundas St / Yonge St,7163.0,Yonge St / Wood St,Member
2,868667,1/4/2017 0:08,1/4/2017 0:14,380,7012.0,Elizabeth St / Edward St (Bus Terminal),7069.0,Queen St W / Spadina Ave,Member
3,868668,1/4/2017 0:12,1/4/2017 0:34,1299,7172.0,Strachan Ave / Princes' Blvd,7069.0,Queen St W / Spadina Ave,Member
4,868669,1/4/2017 0:13,1/4/2017 0:18,323,7039.0,Simcoe St / Dundas St W,7021.0,Bay St / Albert St,Member

In [36]:
df17.info()

<class 'pandas.DataFrame'>
RangeIndex: 1492369 entries, 0 to 1492368
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trip_id                1492369 non-null  int64
 1   trip_start_time        1492369 non-null  str
 2   trip_stop_time         1492369 non-null  str
 3   trip_duration_seconds  1492369 non-null  int64
 4   from_station_id        465476 non-null   float64
 5   from_station_name      1492369 non-null  str
 6   to_station_id          465476 non-null   float64
 7   to_station_name        1492368 non-null  str
 8   user_type              1492369 non-null  str
dtypes: float64(2), int64(2), str(5)
memory usage: 229.3 MB

In [37]:
df17.columns = [c.lower().replace(' ', '_') for c in df17.columns]
df17.columns

Index(['trip_id', 'trip_start_time', 'trip_stop_time', 'trip_duration_seconds',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'user_type'],
      dtype='str')

### 2014-2016

In [38]:
import openpyxl

In [39]:
df16 = pd.read_excel('bikeshare-ridership-2016.xlsx')

In [40]:
df16.isna().sum()

trip_id                  0
trip_start_time          0
trip_stop_time           0
trip_duration_seconds    0
from_station_name        3
to_station_name          2
user_type                0
dtype: int64

In [41]:
df14_15 = pd.read_excel('bikeshare-ridership-2014-2015.xlsx', header=1)
df14_15.head()

  Start Terminal  End Terminal  Casual  Registered  Total
0           7000        7000.0     7.0        24.0     31
1           7000        7001.0     2.0         1.0      3
2           7000        7002.0     NaN         3.0      3
3           7000        7003.0     NaN         5.0      5
4           7000        7004.0     NaN        13.0     13

In [42]:
df16.columns = [c.lower().replace(' ', '_') for c in df16.columns]
df16.columns

Index(['trip_id', 'trip_start_time', 'trip_stop_time', 'trip_duration_seconds',
       'from_station_name', 'to_station_name', 'user_type'],
      dtype='str')

### check column intersaction for each dataframe

In [43]:
#the same for 2024-2025-2026
print(len(df26.columns.intersection(df25.columns))==len(df26.columns))
print(len(df26.columns.intersection(df24.columns))==len(df26.columns))

True
True

In [44]:
len(df26.columns.intersection(df21_23.columns))==len(df26.columns)

False

In [45]:
df26.columns.difference(df21_23.columns)

Index(['bike_model', 'trip_duration'], dtype='str')

In [46]:
df26.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [47]:
df21_23.columns = [c.replace('__', '_') for c in df21_23.columns]
df21_23.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [48]:
df26.columns.difference(df21_23.columns) # no bike_model in 2021-23

Index(['bike_model'], dtype='str')

In [49]:
len(df26.columns.intersection(df20.columns))==len(df26.columns)

False

In [50]:
df26.columns.difference(df20.columns)

Index(['bike_model', 'trip_duration'], dtype='str')

In [51]:
df20.columns = [c.replace('__', '_') for c in df20.columns]
df20.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [52]:
df26.columns.difference(df20.columns) # no bike model for 2020

Index(['bike_model'], dtype='str')

In [53]:
print(len(df26.columns.intersection(df19.columns))==len(df26.columns))
df26.columns.difference(df19.columns)

False

Index(['bike_model', 'trip_duration'], dtype='str')

In [54]:
df19.columns = [c.replace('__', '_') for c in df19.columns]
df19.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [55]:
df26.columns.difference(df19.columns) # no bike model for 2020

Index(['bike_model'], dtype='str')

In [56]:
print(len(df26.columns.intersection(df18.columns))==len(df26.columns))
df26.columns.difference(df18.columns)

False

Index(['bike_id', 'bike_model', 'end_station_id', 'end_station_name',
       'end_time', 'start_station_id', 'start_station_name', 'start_time',
       'trip_duration'],
      dtype='str')

In [233]:
df26.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [57]:
df18.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'}, inplace=True)

In [58]:
df17.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'}, inplace=True)

In [59]:
df16.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'}, inplace=True)

In [60]:
df14_15.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'}, inplace=True)

In [61]:
df14_15.columns

Index(['Start Terminal', 'End Terminal', 'Casual', 'Registered', 'Total'], dtype='str')

In [62]:
df14_15.head()

  Start Terminal  End Terminal  Casual  Registered  Total
0           7000        7000.0     7.0        24.0     31
1           7000        7001.0     2.0         1.0      3
2           7000        7002.0     NaN         3.0      3
3           7000        7003.0     NaN         5.0      5
4           7000        7004.0     NaN        13.0     13

In [63]:
df26.columns.difference(df14_15.columns) # no bike_id and bike_model for 2016

Index(['bike_id', 'bike_model', 'end_station_id', 'end_station_name',
       'end_time', 'start_station_id', 'start_station_name', 'start_time',
       'trip_duration', 'trip_id', 'user_type'],
      dtype='str')

In [64]:
df = pd.concat([df26, df25, df24], ignore_index=True)

In [269]:
df.columns.difference(df18.columns)

Index(['bike_id', 'bike_model'], dtype='str')

In [65]:
df21_23['bike_model'] = 'Unknown'
df20['bike_model'] = 'Unknown'
df19['bike_model'] = 'Unknown'

df18['bike_model'] = 'Unknown'
df18['bike_id'] = 'Unknown'

df17['bike_model'] = 'Unknown'
df17['bike_id'] = 'Unknown'

In [66]:
df21_23 = df21_23.reindex(columns=df.columns)
df20 = df20.reindex(columns=df.columns)
df19 = df19.reindex(columns=df.columns)
df18 = df18.reindex(columns=df.columns)
df17 = df17.reindex(columns=df.columns)

In [67]:
df = pd.concat([df, df21_23, df20, df19, df18, df17])

In [68]:
import parquet

In [69]:
df.start_station_name.unique()

<ArrowStringArray>
[                    'Wolseley St / Augusta Ave',
                 'Union Station (North) - SMART',
                  'Strachan Ave / Princes' Blvd',
         'Lower Spadina Ave / Lake Shore Blvd W',
                        'Temperance St / Bay St',
                'Lower Simcoe St / Bremner Blvd',
                     'Howard St / Sherbourne St',
                       'King St W / Portland St',
              'Spadina Ave / Harbord St - SMART',
              'Baldwin St / Spadina Ave - SMART',
 ...
            'Michael Sweet Ave / St. Patrick St',
                       'Beverly St / College St',
                   'Margueretta St / College St',
                      'Lansdowne Subway Green P',
                        'Roxton Rd / College St',
                                  'Base Station',
 'Lake Shore Blvd W / Ontario Dr(Ontario Place)',
           'Dovercourt Rd / Harrison St - SMART',
        'Summerhill Ave / MacLennan Ave - SMART',
                      'Fringe Next Stage - 7219']
Length: 1635, dtype: str

In [71]:
id_cols = ['trip_id', 'start_station_id', 'end_station_id', 'bike_id']
for col in id_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [72]:
df.to_parquet('bikeshare_all.parquet', index=False)

### station's names check

In [37]:
import re

names = pd.concat([df26['start_station_name'], df26['end_station_name']]).dropna().astype(str).unique()

def normalize(s):
    s = s.lower().strip()
    s = re.sub(r"[.’']", "", s)
    s = re.sub(r"\s+", " ", s)
    return s

groups = {}
for n in names:
    groups.setdefault(normalize(n), []).append(n)

dupe_groups = {k: v for k, v in groups.items() if len(v) > 1}
print(f"{len(dupe_groups)} normalized-duplicate groups out of {len(names)} names")

from difflib import get_close_matches

unique_norms = list(groups.keys())
fuzzy_hits = []
for i, key in enumerate(unique_norms):
    matches = get_close_matches(key, unique_norms[i+1:], n=3, cutoff=0.9)
    for m in matches:
        fuzzy_hits.append((groups[key][0], groups[m][0]))

print(f"{len(fuzzy_hits)} fuzzy near-miss pairs")

0 normalized-duplicate groups out of 1101 names
24 fuzzy near-miss pairs

In [39]:
# for a, b in fuzzy_hits:
#     print(repr(a), "  <->  ", repr(b))

In [153]:
import os
files20 = sorted(os.listdir('bikeshare-ridership-2020'))
for f in files20:
    d = pd.read_csv(os.path.join('bikeshare-ridership-2020', f), nrows=5)
    print(f, list(d.columns), [str(t) for t in d.dtypes])

2020-01.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-02.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-03.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-04.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-05.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-06.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-07.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-08.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-09.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-10.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-11.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']
2020-12.csv ['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time', 'Start Station Name', 'End Station Id', 'End Time', 'End Station Name', 'Bike Id', 'User Type'] ['int64', 'int64', 'int64', 'str', 'str', 'int64', 'str', 'str', 'int64', 'str']

In [154]:
for f in files20:
    d = pd.read_csv(os.path.join('bikeshare-ridership-2020', f))
    dtypes = {c: str(t) for c, t in d.dtypes.items() if c in ['Start Station Id', 'End Station Id', 'Bike Id']}
    print(f, d.shape, dtypes)

2020-01.csv (102148, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-02.csv (95183, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-03.csv (105046, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-04.csv (71779, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-05.csv (196224, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-06.csv (370471, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-07.csv (458884, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-08.csv (494468, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-09.csv (440662, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-10.csv (277839, 10) {'Start Station Id': 'str', 'End Station Id': 'str', 'Bike Id': 'str'}
2020-11.csv (203256, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'int64'}
2020-12.csv (95348, 10) {'Start Station Id': 'int64', 'End Station Id': 'float64', 'Bike Id': 'float64'}

In [155]:
d = pd.read_csv('bikeshare-ridership-2020/2020-10.csv')
for col in ['Start Station Id', 'End Station Id', 'Bike Id']:
    non_numeric = d[col][pd.to_numeric(d[col], errors='coerce').isna() & d[col].notna()]
    print(col, "non-numeric examples:", non_numeric.unique()[:10])

Start Station Id non-numeric examples: <ArrowStringArray>
['10/03/2020 13:28', '10/03/2020 13:38', '10/03/2020 13:48',
 '10/03/2020 13:58', '10/03/2020 14:12', '10/03/2020 14:26',
 '10/03/2020 14:44', '10/03/2020 14:55', '10/03/2020 15:20',
 '10/03/2020 17:03']
Length: 10, dtype: str
End Station Id non-numeric examples: <ArrowStringArray>
['10/03/2020 13:38', '10/03/2020 13:48', '10/03/2020 13:58',
 '10/03/2020 14:12', '10/03/2020 14:26', '10/03/2020 14:44',
 '10/03/2020 14:53', '10/03/2020 15:20', '10/03/2020 15:38',
 '10/03/2020 17:17']
Length: 10, dtype: str
Bike Id non-numeric examples: <ArrowStringArray>
['Annual Member']
Length: 1, dtype: str

In [156]:
bad_mask = pd.to_numeric(d['Start Station Id'], errors='coerce').isna() & d['Start Station Id'].notna()
print(bad_mask.sum(), "affected rows out of", len(d))
d[bad_mask].head(3)

249 affected rows out of 277839

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
25640,10000084625,7120,10/03/2020 13:28,Gerrard St E / River St,7120,10/03/2020 13:38,Gerrard St E / River St,5250,Annual Member,NaN
25837,10000306555,7120,10/03/2020 13:38,Gerrard St E / River St,7576,10/03/2020 13:48,Front St E / Bayview Avenue,5250,Annual Member,NaN
26029,10000519608,7576,10/03/2020 13:48,Front St E / Bayview Avenue,7357,10/03/2020 13:58,Lake Shore Blvd E / Leslie St,5250,Annual Member,NaN