In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import os

### 2026

In [2]:
df26 = pd.read_csv('bikeshare-ridership-2026.csv')

In [3]:
df26.info()

<class 'pandas.DataFrame'>
RangeIndex: 6830174 entries, 0 to 6830173
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    int64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [4]:
df26.isna().sum()

Trip_Id                   0
Trip_Duration             0
Start_Station_Id          0
Start_Time                0
Start_Station_Name        0
End_Station_Id        12951
End_Time               8065
End_Station_Name      12951
Bike_Id                   0
User_Type                 0
Bike_Model                0
dtype: int64

In [7]:
df26.columns = [c.lower().replace(' ', '_') for c in df26.columns]

In [8]:
df26.info()

<class 'pandas.DataFrame'>
RangeIndex: 6830174 entries, 0 to 6830173
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             int64
 1   trip_duration       int64
 2   start_station_id    int64
 3   start_time          str
 4   start_station_name  str
 5   end_station_id      float64
 6   end_time            str
 7   end_station_name    str
 8   bike_id             int64
 9   user_type           str
 10  bike_model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [9]:
before_mem = df26.memory_usage(deep=True).sum() / 1e9
before_mem

np.float64(1.292371323)

In [10]:
df26['start_time'] = pd.to_datetime(df26['start_time'])
df26['end_time'] = pd.to_datetime(df26['end_time'])

In [11]:
before_mem = df26.memory_usage(deep=True).sum() / 1e9
before_mem

np.float64(1.032124101)

In [12]:
df26.bike_model.nunique()
df26.bike_model.unique()

<ArrowStringArray>
['ICONIC', 'EFIT', 'ASTRO']
Length: 3, dtype: str

In [ ]:
# bike_model_map = {'ICONIC': 0, 'EFIT': 1, 'ASTRO': 2, 'Unknown': -1}
# df26['bike_model'] = df26['bike_model'].map(bike_model_map)

In [13]:
df26['user_type'] = df26['user_type'].astype('category')
df26['bike_model'] = df26['bike_model'].astype('category')

In [14]:
# categorizing station_name columns
df26['start_station_name'] = df26['start_station_name'].astype('category')
df26['end_station_name'] = df26['end_station_name'].astype('category')
df26.memory_usage(deep=True).sum() / 1e9

np.float64(0.423546272)

In [15]:
# downcasting numeric columns
int_cols = df26.select_dtypes(include='int64').columns
df26[int_cols] = df26[int_cols].apply(pd.to_numeric, downcast='integer')

float_cols = df26.select_dtypes(include='float64').columns
df26[float_cols] = df26[float_cols].apply(pd.to_numeric, downcast='float')
df26.memory_usage(deep=True).sum() / 1e9

np.float64(0.259622096)

In [16]:
df26.start_time.dt.year.unique()

array([2026], dtype=int32)

In [ ]:
#result - from 1.292371177 GB to 0.259622096 GB

In [17]:
#put all steps into function 
def optimize_df(df):
    df['start_time'] = pd.to_datetime(df['start_time'])
    df['end_time'] = pd.to_datetime(df['end_time'])
    df['bike_model'] = df['bike_model'].astype('category')
    df['user_type'] = df['user_type'].astype('category')
    df['start_station_name'] = df['start_station_name'].astype('category')
    df['end_station_name'] = df['end_station_name'].astype('category')
    int_cols = df.select_dtypes(include='int64').columns
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
    float_cols = df.select_dtypes(include='float64').columns
    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
    return df

### 2025

In [18]:
os.listdir('bikeshare-ridership-2025')

['bikeshare_2025_10.csv',
 'bikeshare_2025_04.csv',
 'bikeshare_2025_05.csv',
 'bikeshare_2025_11.csv',
 'bikeshare_2025_07.csv',
 'bikeshare_2025_12.csv',
 'bikeshare_2025_06.csv',
 'bikeshare_2025_02.csv',
 'bikeshare_2025_03.csv',
 'bikeshare_2025_01.csv',
 'bikeshare_2025_08.csv',
 'bikeshare_2025_09.csv']

In [19]:
files25 = os.listdir('bikeshare-ridership-2025')

monthly_dfs_25 = [
   pd.read_csv(os.path.join('bikeshare-ridership-2025', f), encoding='cp1252') for f in files25
]

In [20]:
df25 = pd.concat(monthly_dfs_25, ignore_index=True)
df25.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,41865752,347,7389.0,2025-10-01 00:01:03,College Park - Gerrard Entrance,7693.0,2025-10-01 00:06:50,College Park - Gerrard Entrance,5579,Member,ICONIC
1,41865762,806,7485.0,2025-10-01 00:02:49,Blythwood Rd / Yonge St - SMART,7676.0,2025-10-01 00:16:15,Blythwood Rd / Yonge St - SMART,6681,Casual,EFIT
2,41865748,321,7030.0,2025-10-01 00:00:32,Bay St / Wellesley St W,7058.0,2025-10-01 00:05:53,Bay St / Wellesley St W,1392,Casual,ICONIC
3,41865749,125,7386.0,2025-10-01 00:00:48,D'Arcy St / McCaul St - SMART,7257.0,2025-10-01 00:02:53,D'Arcy St / McCaul St - SMART,2545,Member,ICONIC
4,41865767,782,7894.0,2025-10-01 00:03:23,Millwood Rd / Southvale Dr,7194.0,2025-10-01 00:16:25,Millwood Rd / Southvale Dr,9947,Member,EFIT

In [21]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 7812520 entries, 0 to 7812519
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    float64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(2), int64(3), str(6)
memory usage: 1.4 GB

In [22]:
df25.columns = [c.lower().replace(' ', '_') for c in df25.columns]
df25.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [23]:
df25.memory_usage(deep=True).sum() / 1e9

np.float64(1.484327276)

In [24]:
df25 = optimize_df(df25)

df25.memory_usage(deep=True).sum()/ 1e9

np.float64(0.31257724)

In [ ]:
#from 1.484543626 GB to  0.31257724 GB for 2025

In [25]:
df25.start_time.dt.year.unique()

array([2025], dtype=int32)

In [129]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 7812520 entries, 0 to 7812519
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             int32
 1   trip_duration       int32
 2   start_station_id    float32
 3   start_time          datetime64[us]
 4   start_station_name  category
 5   end_station_id      float32
 6   end_time            datetime64[us]
 7   end_station_name    category
 8   bike_id             int16
 9   user_type           category
 10  bike_model          category
dtypes: category(4), datetime64[us](2), float32(2), int16(1), int32(2)
memory usage: 298.1 MB

### 2024

In [26]:
df24 = pd.read_csv('bikeshare-ridership-2024.csv')

In [12]:
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 6953094 entries, 0 to 6953093
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip_Id             int64
 1   Trip_Duration       int64
 2   Start_Station_Id    int64
 3   Start_Time          str
 4   Start_Station_Name  str
 5   End_Station_Id      float64
 6   End_Time            str
 7   End_Station_Name    str
 8   Bike_Id             int64
 9   User_Type           str
 10  Bike_Model          str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.2 GB

In [27]:
df24.isna().sum()

Trip_Id                  0
Trip_Duration            0
Start_Station_Id         0
Start_Time               0
Start_Station_Name       0
End_Station_Id        8424
End_Time              5822
End_Station_Name      8424
Bike_Id                  0
User_Type                0
Bike_Model               0
dtype: int64

In [28]:
df24.columns = [c.lower().replace(' ', '_') for c in df24.columns]
df24.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model'],
      dtype='str')

In [29]:
df24.memory_usage(deep=True).sum() / 1e9

np.float64(1.324307511)

In [30]:
df24 = optimize_df(df24)
df24.memory_usage(deep=True).sum() / 1e9

np.float64(0.264278176)

In [ ]:
# 1.324427269 -> 0.264278176 GB

In [31]:
del monthly_dfs_25
import gc; gc.collect()

238

In [32]:
df24.start_time.dt.year.unique()

array([2024], dtype=int32)

### 2021 - 2023

In [33]:
folders21_23  = [l for l in os.listdir() if '2021' in l or '2022' in l or '2023' in l]
folders21_23

['bikeshare-ridership-2023',
 'bikeshare-ridership-2022',
 'bikeshare-ridership-2021']

In [34]:
months = [f"0{i}" if i< 10 else f"{i}" for i in range(1, 13)]

In [35]:
def month_path(folder, month):
    p = f"{folder}/Bike share ridership {folder[-4:]}-{month}"
    return f"{p}.csv" if os.path.exists(f"{p}.csv") else f"{p}.zip"

months = [f"0{i}" if i < 10 else f"{i}" for i in range(1, 13)]
monthly_dfs = [
    pd.read_csv(month_path(folder, month), encoding='cp1252')
    for folder in folders21_23
    for month in months
]
df21_23 = pd.concat(monthly_dfs, ignore_index=True)
df21_23.shape

(13908792, 11)

In [36]:
df21_23['Trip Id'] = df21_23['Trip Id'].combine_first(df21_23['ï»¿Trip Id'])

In [37]:
df21_23.drop('ï»¿Trip Id', axis = 1, inplace=True)

/var/folders/xf/ygl5_zk57kn1rh2h1xj9fyx40000gn/T/ipykernel_68804/2831461403.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df21_23.drop('ï»¿Trip Id', axis = 1, inplace=True)

In [38]:
df21_23.columns = [c.lower().replace(' ', '_') for c in df21_23.columns]

cols = [col for col in df21_23.columns if col != 'trip_id']
df21_23 = df21_23[['trip_id'] + cols]
df21_23.head()

,trip_id,trip__duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type
0,20148784.0,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770.0,Casual Member
1,20148785.0,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400.0,Casual Member
2,20148786.0,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068.0,Annual Member
3,20148790.0,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427.0,Casual Member
4,20148791.0,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840.0,Casual Member

In [32]:
df21_23.info()

<class 'pandas.DataFrame'>
RangeIndex: 13908792 entries, 0 to 13908791
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             float64
 1   trip__duration      int64
 2   start_station_id    int64
 3   start_time          str
 4   start_station_name  str
 5   end_station_id      float64
 6   end_time            str
 7   end_station_name    str
 8   bike_id             float64
 9   user_type           str
dtypes: float64(3), int64(2), str(5)
memory usage: 2.3 GB

In [39]:
df21_23.columns = [c.replace('__', '_') for c in df21_23.columns]
df21_23.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [40]:
# #put all steps into function 
# def optimize_df(df):
#     df['start_time'] = pd.to_datetime(df['start_time'])
#     df['end_time'] = pd.to_datetime(df['end_time'])
    

#     df['bike_model'] = df['bike_model'].astype('category')
        
#     df['user_type'] = df['user_type'].astype('category')
#     df['start_station_name'] = df['start_station_name'].astype('category')
#     df['end_station_name'] = df['end_station_name'].astype('category')
#     int_cols = df.select_dtypes(include='int64').columns
#     df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
#     float_cols = df.select_dtypes(include='float64').columns
#     df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
#     return df

def optimize_df(df):
    # datetime
    if 'start_time' in df.columns:
        df['start_time'] = pd.to_datetime(df['start_time'])
    if 'end_time' in df.columns:
        df['end_time'] = pd.to_datetime(df['end_time'])
    # category
    for col in ['bike_model', 'user_type', 'start_station_name', 'end_station_name']:
        if col in df.columns:
            df[col] = df[col].astype('category')
    # downcast
    int_cols = df.select_dtypes(include='int64').columns
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
    float_cols = df.select_dtypes(include='float64').columns
    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
    return df

In [41]:
df21_23.memory_usage(deep=True).sum()/1e9

np.float64(2.446728522)

In [42]:
df21_23 = optimize_df(df21_23)
df21_23.memory_usage(deep=True).sum()/1e9

np.float64(0.598131214)

In [43]:
df21_23.start_time.dt.year.unique()

array([2023, 2022, 2021], dtype=int32)

In [37]:
df21_23.dtypes

trip_id                      float64
trip_duration                  int32
start_station_id               int16
start_time            datetime64[us]
start_station_name          category
end_station_id               float32
end_time              datetime64[us]
end_station_name            category
bike_id                      float32
user_type                   category
dtype: object

In [127]:
# from 2.446753743 to 0.598131214 GB
# del df21_23

### 2020

In [40]:
# monthly_dfs_20 = [
#     pd.read_csv(os.path.join('bikeshare-ridership-2020', file)) for file in os.listdir('bikeshare-ridership-2020')
# ]

In [44]:
# connandrum with 2020-10
# problem with 2020-10.csv, 249 rows are missing the Trip Duration field entirely, 
# which shifts every subsequent column one position to the left for those rows. 
df20_10 = pd.read_csv(os.path.join('bikeshare-ridership-2020/2020-10.csv'))

In [45]:
df20_10 = df20_10.astype('object')

In [46]:
cols = df20_10.columns.tolist()

In [47]:
bad_rows = pd.to_numeric(df20_10[cols[2]], errors='coerce').isna() & df20_10[cols[2]].notna()

# df20_10.loc[bad_rows, cols[2:]].dtypes
df20_10.loc[bad_rows, cols[2:]] = df20_10.loc[bad_rows, cols[1:-1]].values
# df20_10.loc[bad_rows, cols[1]] = np.nan

In [48]:
df20_10.loc[bad_rows, cols[1]] = np.nan

In [49]:
# rest of the 2020 except corrupted 10/20: 

monthly_dfs_20 = [
    pd.read_csv(os.path.join('bikeshare-ridership-2020', file)) for file in os.listdir('bikeshare-ridership-2020') if file !='2020-10.csv'
]

In [50]:
df20 = pd.concat(monthly_dfs_20, ignore_index=True)
df20.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,7452736,625,7162,02/01/2020 00:00,Hayter St / Laplante Ave,7190.0,02/01/2020 00:11,St. George St / Hoskin Ave,653.0,Annual Member
1,7452737,426,7170,02/01/2020 00:01,Spadina Ave / Willcocks St,7239.0,02/01/2020 00:08,Bloor St W / Manning Ave - SMART,4682.0,Annual Member
2,7452738,817,7475,02/01/2020 00:03,Jarvis St / Richmond St E,7075.0,02/01/2020 00:16,Queens Quay W / Dan Leckie Way,3852.0,Annual Member
3,7452739,653,7099,02/01/2020 00:03,Cherry St / Mill St,7292.0,02/01/2020 00:14,Granby St / Church St - SMART,4546.0,Annual Member
4,7452740,189,7176,02/01/2020 00:03,Bathurst St / Fort York Blvd,7402.0,02/01/2020 00:06,Wellington St W / Bathurst St,4867.0,Annual Member

In [51]:
df20.columns = [c.lower().replace(' ', '_') for c in df20.columns]
df20.columns = [c.lower().replace('__', '_') for c in df20.columns]
df20.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [119]:
import numpy as np

In [196]:
sample_idx = np.random.choice(df20.shape[0], 15)
print(df20['start_time'].iloc[sample_idx].tolist())

['08/14/2020 17:46', '07/10/2020 19:51', '10/04/2020 11:58', '11/01/2020 07:55', '07/25/2020 16:52', '09/25/2020 16:53', '07/21/2020 23:41', '11/13/2020 14:29', '09/05/2020 18:03', '07/01/2020 13:05', '10/10/2020 19:58', '09/25/2020 19:27', '09/13/2020 15:41', '06/19/2020 09:34', '12/18/2020 19:08']

In [52]:
pd.to_datetime(df20['start_time'])

0         2020-02-01 00:00:00
1         2020-02-01 00:01:00
2         2020-02-01 00:03:00
3         2020-02-01 00:03:00
4         2020-02-01 00:03:00
                  ...
2633464   2020-09-30 23:59:00
2633465   2020-09-30 23:59:00
2633466   2020-09-30 23:59:00
2633467   2020-09-30 23:59:00
2633468   2020-09-30 23:59:00
Name: start_time, Length: 2633469, dtype: datetime64[us]

In [53]:
df20 = optimize_df(df20)

In [54]:
df20.memory_usage(deep=True).sum()/1e9

np.float64(0.102749032)

In [55]:
df20_10.columns = [c.lower().replace(' ', '_') for c in df20_10.columns]
df20_10.columns = [c.lower().replace('__', '_') for c in df20_10.columns]
df20_10.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [56]:
pd.to_datetime(df20_10['start_time'])

0        2020-10-01 00:00:00
1        2020-10-01 00:00:00
2        2020-10-01 00:01:00
3        2020-10-01 00:01:00
4        2020-10-01 00:01:00
                 ...
277834   2020-10-31 23:57:00
277835   2020-10-31 23:57:00
277836   2020-10-31 23:58:00
277837   2020-10-31 23:59:00
277838   2020-10-31 23:59:00
Name: start_time, Length: 277839, dtype: datetime64[us]

In [57]:
df20_10 = optimize_df(df20_10)

In [58]:
df20 = pd.concat([df20, df20_10], ignore_index=True)

In [59]:
df20.memory_usage(deep=True).sum()/1e9

np.float64(0.774862906)

In [60]:
df20 = optimize_df(df20)
df20.memory_usage(deep=True).sum()/1e9

np.float64(0.578282797)

In [61]:
df20 = df20.sort_values('start_time')

In [62]:
df20.dtypes

trip_id                       object
trip_duration                 object
start_station_id              object
start_time            datetime64[us]
start_station_name          category
end_station_id                object
end_time              datetime64[us]
end_station_name            category
bike_id                       object
user_type                   category
dtype: object

In [64]:
df20.start_time.dt.year.unique()

array([2020], dtype=int32)

### 2019

In [65]:
quaterly_dfs_19 = [
    
     pd.read_csv(os.path.join('bikeshare-ridership-2019', file)) for file in os.listdir('bikeshare-ridership-2019')

]

In [66]:
df19 = pd.concat(quaterly_dfs_19, ignore_index=True)
df19.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,5533843,1834.0,7352,07/01/2019 00:00,Cosburn Ave / Donlands Ave,7352.0,07/01/2019 00:30,Cosburn Ave / Donlands Ave,989,Casual Member
1,5533844,338.0,7016,07/01/2019 00:00,Bay St / Queens Quay W (Ferry Terminal),7068.0,07/01/2019 00:06,Dockside Dr / Queens Quay E (Sugar Beach),4006,Annual Member
2,5533845,1433.0,7193,07/01/2019 00:00,Queen St W / Gladstone Ave,7285.0,07/01/2019 00:24,Spadina Ave / Harbord St - SMART,1512,Casual Member
3,5533846,1042.0,7369,07/01/2019 00:00,Dupont St / Emerson Ave SMART,7239.0,07/01/2019 00:18,Bloor St W / Manning Ave - SMART,3219,Casual Member
4,5533847,4203.0,7168,07/01/2019 00:01,Queens Quay / Yonge St,7226.0,07/01/2019 01:11,Lake Shore Blvd W / The Boulevard Club,4425,Casual Member

In [67]:
df19.info()

<class 'pandas.DataFrame'>
RangeIndex: 2439517 entries, 0 to 2439516
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   Trip Id             int64
 1   Trip  Duration      float64
 2   Start Station Id    int64
 3   Start Time          str
 4   Start Station Name  str
 5   End Station Id      float64
 6   End Time            str
 7   End Station Name    str
 8   Bike Id             int64
 9   User Type           str
dtypes: float64(2), int64(3), str(5)
memory usage: 418.3 MB

In [122]:
df19.columns = [c.lower().replace(' ', '_') for c in df19.columns]
df19.columns = [c.lower().replace('__', '_') for c in df19.columns]
df19.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type'],
      dtype='str')

In [69]:
df19 = optimize_df(df19)
df19.memory_usage(deep=True).sum()/1e9

np.float64(0.090295951)

In [70]:
df19.start_time.dt.year.unique()

array([2019], dtype=int32)

In [124]:
df19.memory_usage(deep=True).sum()/1e9

np.float64(0.090295951)

### 2018

In [71]:
quaterly_dfs_18 = [
     pd.read_csv(os.path.join('bikeshare2018', file)) for file in os.listdir('bikeshare2018')
]

In [72]:
df18 = pd.concat(quaterly_dfs_18, ignore_index=True)
df18.head()

,trip_id,trip_duration_seconds,from_station_id,trip_start_time,from_station_name,trip_stop_time,to_station_id,to_station_name,user_type
0,3244396,528,7254,7/1/2018 0:00,Borden St / Bloor St W - SMART,7/1/2018 0:08,7140,Macpherson Ave / Spadina Rd,Annual Member
1,3244398,570,7031,7/1/2018 0:00,Jarvis St / Isabella St,7/1/2018 0:09,7167,Queen St E / George St (Moss Park),Annual Member
2,3244397,368,7286,7/1/2018 0:00,Gerrard St E / Broadview - SMART,7/1/2018 0:06,7286,Gerrard St E / Broadview - SMART,Casual Member
3,3244399,1147,7248,7/1/2018 0:00,Baldwin Ave / Spadina Ave - SMART,7/1/2018 0:19,7020,Phoebe St / Spadina Ave,Annual Member
4,3244400,730,7207,7/1/2018 0:02,Dundas St W / Crawford St,7/1/2018 0:14,7000,Fort York Blvd / Capreol Ct,Annual Member

In [32]:
df18.info()

<class 'pandas.DataFrame'>
RangeIndex: 1922955 entries, 0 to 1922954
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trip_id                int64
 1   trip_duration_seconds  int64
 2   from_station_id        int64
 3   trip_start_time        str
 4   from_station_name      str
 5   trip_stop_time         str
 6   to_station_id          int64
 7   to_station_name        str
 8   user_type              str
dtypes: int64(4), str(5)
memory usage: 309.0 MB

In [73]:
df18.columns = [c.lower().replace(' ', '_') for c in df18.columns]
df18.columns

Index(['trip_id', 'trip_duration_seconds', 'from_station_id',
       'trip_start_time', 'from_station_name', 'trip_stop_time',
       'to_station_id', 'to_station_name', 'user_type'],
      dtype='str')

In [75]:
d18 = df18.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'})

In [76]:
df18 = optimize_df(df18)
df18.memory_usage(deep=True).sum()/1e9

np.float64(0.063482954)

In [79]:
df18.start_time.dt.year.unique()

array([2018], dtype=int32)

In [120]:
df18.info()

<class 'pandas.DataFrame'>
RangeIndex: 1922955 entries, 0 to 1922954
Data columns (total 9 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             int32
 1   trip_duration       int32
 2   start_station_id    int16
 3   start_time          datetime64[us]
 4   start_station_name  category
 5   end_time            datetime64[us]
 6   end_station_id      int16
 7   end_station_name    category
 8   user_type           category
dtypes: category(3), datetime64[us](2), int16(2), int32(2)
memory usage: 60.5 MB

### 2017

In [ ]:
# each quarter differs with date format.

In [80]:
def parse_dt(s):
    first = pd.to_numeric(s.dropna().astype(str).str.split('/').str[0], errors='coerce')
    return pd.to_datetime(s, dayfirst=bool((first > 12).any()), format='mixed', errors='coerce')


quaterly_dfs_17 = []
for file in os.listdir('2017 Data'):
    tmp = pd.read_csv(os.path.join('2017 Data', file))
    tmp['trip_start_time'] = parse_dt(tmp['trip_start_time'])
    tmp['trip_stop_time'] = parse_dt(tmp['trip_stop_time'])
    quaterly_dfs_17.append(tmp)

In [81]:
df17 = pd.concat(quaterly_dfs_17, ignore_index=True)
df17.head()

,trip_id,trip_start_time,trip_stop_time,trip_duration_seconds,from_station_id,from_station_name,to_station_id,to_station_name,user_type
0,868665,2017-04-01 00:01:00,2017-04-01 00:06:00,297,7073.0,Bremner Blvd / Spadina Ave,7211.0,Fort York Blvd / Garrison Rd,Member
1,868666,2017-04-01 00:07:00,2017-04-01 00:11:00,236,7038.0,Dundas St / Yonge St,7163.0,Yonge St / Wood St,Member
2,868667,2017-04-01 00:08:00,2017-04-01 00:14:00,380,7012.0,Elizabeth St / Edward St (Bus Terminal),7069.0,Queen St W / Spadina Ave,Member
3,868668,2017-04-01 00:12:00,2017-04-01 00:34:00,1299,7172.0,Strachan Ave / Princes' Blvd,7069.0,Queen St W / Spadina Ave,Member
4,868669,2017-04-01 00:13:00,2017-04-01 00:18:00,323,7039.0,Simcoe St / Dundas St W,7021.0,Bay St / Albert St,Member

In [82]:
df17.info()

<class 'pandas.DataFrame'>
RangeIndex: 1492369 entries, 0 to 1492368
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trip_id                1492369 non-null  int64
 1   trip_start_time        1492369 non-null  datetime64[us]
 2   trip_stop_time         1492368 non-null  datetime64[us]
 3   trip_duration_seconds  1492369 non-null  int64
 4   from_station_id        465476 non-null   float64
 5   from_station_name      1492369 non-null  str
 6   to_station_id          465476 non-null   float64
 7   to_station_name        1492368 non-null  str
 8   user_type              1492369 non-null  str
dtypes: datetime64[us](2), float64(2), int64(2), str(3)
memory usage: 185.6 MB

In [83]:
df17.columns = [c.lower().replace(' ', '_') for c in df17.columns]
df17.columns

Index(['trip_id', 'trip_start_time', 'trip_stop_time', 'trip_duration_seconds',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'user_type'],
      dtype='str')

In [85]:
df17 = df17.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'})

In [86]:
df17 = optimize_df(df17)
df17.memory_usage(deep=True).sum()/1e9

np.float64(0.055238522)

In [87]:
df17.start_time.dt.year.unique()

array([2017], dtype=int32)

In [119]:
df17.info()

<class 'pandas.DataFrame'>
RangeIndex: 1492369 entries, 0 to 1492368
Data columns (total 9 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   trip_id             1492369 non-null  int32
 1   start_time          1492369 non-null  datetime64[us]
 2   end_time            1492368 non-null  datetime64[us]
 3   trip_duration       1492369 non-null  int32
 4   start_station_id    465476 non-null   float32
 5   start_station_name  1492369 non-null  category
 6   end_station_id      465476 non-null   float32
 7   end_station_name    1492368 non-null  category
 8   user_type           1492369 non-null  category
dtypes: category(3), datetime64[us](2), float32(2), int32(2)
memory usage: 52.7 MB

### 2016

In [88]:
import openpyxl

In [89]:
df16 = pd.read_excel('bikeshare-ridership-2016.xlsx')

In [90]:
df16.isna().sum()

trip_id                  0
trip_start_time          0
trip_stop_time           0
trip_duration_seconds    0
from_station_name        3
to_station_name          2
user_type                0
dtype: int64

In [91]:
df16.columns = [c.lower().replace(' ', '_') for c in df16.columns]
df16.columns

Index(['trip_id', 'trip_start_time', 'trip_stop_time', 'trip_duration_seconds',
       'from_station_name', 'to_station_name', 'user_type'],
      dtype='str')

In [93]:
d16 = df16.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'})

In [118]:
df16.info()

<class 'pandas.DataFrame'>
RangeIndex: 367962 entries, 0 to 367961
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_id             367962 non-null  int32
 1   start_time          367962 non-null  datetime64[us]
 2   end_time            367962 non-null  datetime64[us]
 3   trip_duration       367962 non-null  int16
 4   start_station_name  367959 non-null  category
 5   end_station_name    367960 non-null  category
 6   user_type           367962 non-null  category
dtypes: category(3), datetime64[us](2), int16(1), int32(1)
memory usage: 9.5 MB

In [95]:
df16 = optimize_df(df16)
df16.memory_usage(deep=True).sum()/1e9

np.float64(0.009948705)

In [96]:
df16.start_time.dt.year.unique()

array([2016, 2000], dtype=int32)

In [97]:
d16[d16.start_time.dt.year==2000]

,trip_id,start_time,end_time,trip_duration,start_station_name,end_station_name,user_type
365004,622515,2000-01-01 14:40:00,2000-01-01 15:44:00,3794,Front St / Yonge St (Hockey Hall of Fame),Front St / Yonge St (Hockey Hall of Fame),Member

In [ ]:
d16[d16.trip_id<622515].sort_values('trip_id', ascending=False)

,trip_id,start_time,end_time,trip_duration,start_station_name,end_station_name,user_type
91687,462304,2016-09-30 23:59:00,2016-10-01 00:12:00,771,80 Clinton St (North of College),424 Wellington St. W,Member
361055,462303,2016-09-30 23:59:00,2016-10-01 00:04:00,317,Wellesley St E / Yonge St Green P,Hayter St / Laplante Ave,Member
48925,462302,2016-09-30 23:59:00,2016-10-01 00:04:00,341,Queen St W / Spadina Ave,Augusta Ave / Denison Sq,Member
270823,462301,2016-09-30 23:59:00,2016-10-01 00:13:00,880,Dockside Dr / Queens Quay E (Sugar Beach),Queen St E / Berkely St,Member
67715,462300,2016-09-30 23:57:00,2016-10-01 00:06:00,556,Dundas St E / Regent Park Blvd,King St E / Jarvis St,Member
...,...,...,...,...,...,...,...
128416,24012,2016-07-01 00:01:00,2016-07-01 00:12:00,662,Simcoe St / Queen St W,Queen St W / Spadina Ave,Member
169223,24011,2016-07-01 00:01:00,2016-07-01 00:07:00,399,Trinity St /Front St E,Princess St / Adelaide St,Member
172573,24010,2016-07-01 00:00:00,2016-07-01 00:42:00,2487,Bay St / Queens Quay W (Ferry Terminal),York St / Queens Quay W,Casual
110732,24009,2016-07-01 00:00:00,2016-07-01 00:10:00,603,Wellington St W / Bay St,King St W / Spadina Ave,Member
35445,24008,2016-07-01 00:00:00,2016-07-01 00:08:00,505,College St W / Huron St,Queens Park / Bloor St W,Member

In [106]:
d16.sort_values('start_time', ascending=False).head()

,trip_id,start_time,end_time,trip_duration,start_station_name,end_station_name,user_type
361055,462303,2016-09-30 23:59:00,2016-10-01 00:04:00,317,Wellesley St E / Yonge St Green P,Hayter St / Laplante Ave,Member
48925,462302,2016-09-30 23:59:00,2016-10-01 00:04:00,341,Queen St W / Spadina Ave,Augusta Ave / Denison Sq,Member
270823,462301,2016-09-30 23:59:00,2016-10-01 00:13:00,880,Dockside Dr / Queens Quay E (Sugar Beach),Queen St E / Berkely St,Member
91687,462304,2016-09-30 23:59:00,2016-10-01 00:12:00,771,80 Clinton St (North of College),424 Wellington St. W,Member
67715,462300,2016-09-30 23:57:00,2016-10-01 00:06:00,556,Dundas St E / Regent Park Blvd,King St E / Jarvis St,Member

In [108]:
d16 = d16[~d16.start_time.dt.year==2000]

### 2014-2015

In [292]:
df14_15 = pd.read_excel('bikeshare-ridership-2014-2015.xlsx', header=1)
df14_15.head()

  Start Terminal  End Terminal  Casual  Registered  Total
0           7000        7000.0     7.0        24.0     31
1           7000        7001.0     2.0         1.0      3
2           7000        7002.0     NaN         3.0      3
3           7000        7003.0     NaN         5.0      5
4           7000        7004.0     NaN        13.0     13

In [ ]:
df14_15.rename(columns={'trip_duration_seconds':'trip_duration', 
                        'from_station_id':'start_station_id',
                        'trip_start_time':'start_time', 
                        'from_station_name':'start_station_name', 
                        'to_station_id':'end_station_id', 
                        'to_station_name':'end_station_name', 
                        'trip_stop_time':'end_time'}, inplace=True)

In [62]:
df14_15.head()

  Start Terminal  End Terminal  Casual  Registered  Total
0           7000        7000.0     7.0        24.0     31
1           7000        7001.0     2.0         1.0      3
2           7000        7002.0     NaN         3.0      3
3           7000        7003.0     NaN         5.0      5
4           7000        7004.0     NaN        13.0     13

In [63]:
df26.columns.difference(df14_15.columns) # no bike_id and bike_model for 2016

Index(['bike_id', 'bike_model', 'end_station_id', 'end_station_name',
       'end_time', 'start_station_id', 'start_station_name', 'start_time',
       'trip_duration', 'trip_id', 'user_type'],
      dtype='str')

In [68]:
import parquet

### concatenate and save

In [131]:
df = pd.concat([df26, df25, df24, df21_23, df20, df19, df18, df17, df16])

In [132]:
def optimize_df(df):
    if 'start_time' in df.columns:
        df['start_time'] = pd.to_datetime(df['start_time'])
    if 'end_time' in df.columns:
        df['end_time'] = pd.to_datetime(df['end_time'])

    for col in ['bike_model', 'user_type', 'start_station_name', 'end_station_name']:
        if col in df.columns:
            df[col] = df[col].astype('category')

    for col in ['trip_id', 'trip_duration', 'start_station_id', 'end_station_id', 'bike_id']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    int_cols = df.select_dtypes(include='int64').columns
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast='integer')
    float_cols = df.select_dtypes(include='float64').columns
    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast='float')
    return df

In [133]:
df = optimize_df(df)

In [134]:
df.dtypes

trip_id                        int64
trip_duration                float32
start_station_id             float32
start_time            datetime64[us]
start_station_name          category
end_station_id               float32
end_time              datetime64[us]
end_station_name            category
bike_id                      float32
user_type                   category
bike_model                  category
dtype: object

In [135]:
df.memory_usage(deep=True).sum()/1e9

np.float64(2.41059854)

In [117]:
df.columns

Index(['trip_id', 'trip_duration', 'start_station_id', 'start_time',
       'start_station_name', 'end_station_id', 'end_time', 'end_station_name',
       'bike_id', 'user_type', 'bike_model', 'trip__duration'],
      dtype='str')

In [137]:
del df26, df25, df24, df21_23, df20, df19, df18, df17, df16

In [138]:
gc.collect()

462

In [136]:
df.to_parquet('bikeshare_all.parquet', index=False)

## Information recovery for trip_duration

In [2]:
df = pd.read_parquet('bikeshare_all.parquet')

In [3]:
df['trip_duration_calc'] = (df['end_time'] - df['start_time']).dt.total_seconds()

In [4]:
df.loc[(df['trip_duration']==0) & (df['trip_duration_calc']!=0) & ~df['trip_duration_calc'].isna() & (df['trip_duration_calc']>0)].shape

(32, 12)

In [5]:
print(df['trip_duration'].isna().sum())
print(df[df['trip_duration']==0].shape[0])

265
44570

In [6]:
df[(df['trip_duration']==0) & (df['start_time']==df['end_time'])].shape[0]

29558

In [7]:
# i think we can skip all the trips above where trip_duration==0 and start/end time the same
mask = (df['trip_duration']==0) & (df['start_time']==df['end_time'])
df = df[~mask]

In [9]:
print(df['trip_duration'].isna().sum())
print(df[df['trip_duration']==0].shape[0])

265
15012

In [ ]:
# fill trip_duration (==0) with trip_duration_calc (end_time-start_time)
mask = (df['trip_duration']==0) & (df['trip_duration_calc']>0)
df.loc[mask, 'trip_duration'] = df.loc[mask, 'trip_duration_calc']

In [11]:
print(df['trip_duration'].isna().sum())
print(df[df['trip_duration']==0].shape[0])

265
14980

In [12]:
df[df['trip_duration']==0].start_time.dt.year.value_counts()

start_time
2026    8065
2024    5822
2025    1092
2017       1
Name: count, dtype: int64

In [13]:
df[(df['trip_duration']==0) & (df.start_time.dt.year==2017)]
# we can remove smth like that, it's not informative

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model,trip_duration_calc
44070839,2302635,0.0,NaN,2017-11-29 05:53:54,Seaton St / Dundas St E,NaN,NaT,NaN,NaN,Casual,NaN,NaN

In [185]:
df[(df['trip_duration']==0) & (df.start_time.dt.year==2026)].head()
# in this case there are plenty of information, let's dive deeper

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model,trip_duration_calc
3821,43687212,0.0,7240.0,2026-01-02 14:38:08,Bloor St W / Shaw St - SMART,NaN,NaT,NaN,289.0,Member,ICONIC,NaN
6965,43691231,0.0,7322.0,2026-01-03 11:30:50,East Liberty St / Western Battery Rd,8023.0,NaT,Shaw St / College St,6062.0,Member,ICONIC,NaN
7364,43691833,0.0,7150.0,2026-01-03 13:05:01,Dufferin St / Sylvan Av (Dufferin Grove Park),8023.0,NaT,Shaw St / College St,5825.0,Member,ICONIC,NaN
18005,43705519,0.0,8180.0,2026-01-06 08:17:55,Osler Playground (Argyle St),NaN,NaT,NaN,3083.0,Casual,ICONIC,NaN
19260,43706967,0.0,7933.0,2026-01-06 10:05:57,Elizabeth St / Elm St,NaN,NaT,NaN,4354.0,Casual,ICONIC,NaN

In [14]:
# check where user arrived to the other station:
df[(df['trip_duration']==0) & (df['start_station_id']!=df['end_station_id'])].shape[0]

14559

In [197]:
df.shape[0] - 14559

44594574

In [15]:
# can remove with trip_duration==0 and start/end station the same (421 obs)
mask = (df['trip_duration']==0) & (df['start_station_id']==df['end_station_id'])
df = df.loc[~mask]

In [16]:
print(df['trip_duration'].isna().sum())
print(df[df['trip_duration']==0].shape[0])

265
14559

In [ ]:
# get rid of obs. where we do not know start_station_id and trip_duration==0
mask = (df['trip_duration']==0) & (df['start_station_id'].isna())
df = df[~mask]

In [28]:
df[(df['trip_duration']==0)]['end_station_id'].notna().mean()

np.float64(0.3872097815634016)

In [ ]:
# about 40% trips with trip_duration=0 but at the same time end_station_id!=start_station_id
# so it can't be zero duration

In [33]:
(df[(df['trip_duration']==0) & (df['end_station_id'].notna())]
        .sort_values(['start_station_id', 'start_time'])
        .head()) # 5637

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model,trip_duration_calc
17536898,30003946,0.0,7000.0,2024-07-09 22:40:55,Fort York Blvd / Capreol Ct,7762.0,NaT,College St / Henry St,1178.0,Member,ICONIC,NaN
17536903,30003951,0.0,7000.0,2024-07-09 22:41:06,Fort York Blvd / Capreol Ct,7762.0,NaT,College St / Henry St,3466.0,Member,ICONIC,NaN
17643206,30127130,0.0,7000.0,2024-07-14 01:48:06,Fort York Blvd / Capreol Ct,7768.0,NaT,Armoury St / Chestnut St,3692.0,Member,ICONIC,NaN
17920399,30446161,0.0,7000.0,2024-07-23 15:38:44,Fort York Blvd / Capreol Ct,7322.0,NaT,East Liberty St / Western Battery Rd,2847.0,Casual,ICONIC,NaN
17964633,30496028,0.0,7000.0,2024-07-24 21:00:32,Fort York Blvd / Capreol Ct,7176.0,NaT,Bathurst St / Fort York Blvd,646.0,Member,ICONIC,NaN

In [34]:
(df[(df['trip_duration']==0) & (df['end_station_id'].isna())]
        .sort_values(['start_station_id', 'start_time'])
        .head())

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model,trip_duration_calc
18274498,30854816,0.0,7000.0,2024-08-03 23:04:30,Fort York Blvd / Capreol Ct,NaN,NaT,NaN,2824.0,Casual,ICONIC,NaN
18340178,30932697,0.0,7000.0,2024-08-06 19:31:03,Fort York Blvd / Capreol Ct,NaN,NaT,NaN,8184.0,Casual,EFIT G5,NaN
18340235,30932759,0.0,7000.0,2024-08-06 19:31:57,Fort York Blvd / Capreol Ct,NaN,NaT,NaN,4129.0,Casual,ICONIC,NaN
18366378,30963114,0.0,7000.0,2024-08-07 17:37:43,Fort York Blvd / Capreol Ct,NaN,NaT,NaN,8105.0,Casual,EFIT G5,NaN
18379670,30977829,0.0,7000.0,2024-08-07 23:57:12,Fort York Blvd / Capreol Ct,NaN,NaT,NaN,7329.0,Casual,ICONIC,NaN

In [38]:
# i can assume it's invalid trips, and try to remove them for the further analysis. They doesn't look like a real trip, rather uder's try
mask = (df['trip_duration']==0) & (df['end_station_id'].isna())
df = df[~mask]

In [39]:
df[df['trip_duration']==0].start_time.dt.year.value_counts()

start_time
2026    3132
2024    2331
2025     174
Name: count, dtype: int64

In [40]:
df[df['trip_duration'].isna()].start_time.dt.year.value_counts()

start_time
2020    249
2019     16
Name: count, dtype: int64

In [42]:
# let's coalesce trip_duration with trip_duration_calc (end_time-start_time)
df['trip_duration'] = df['trip_duration'].combine_first(df['trip_duration_calc'])

In [43]:
df[df['trip_duration'].isna()].start_time.dt.year.value_counts()

Series([], Name: count, dtype: int64)

In [44]:
df[df['trip_duration']==0].start_time.dt.year.value_counts()

start_time
2026    3132
2024    2331
2025     174
2019      14
Name: count, dtype: int64

In [48]:
df[(df['trip_duration']==0) & (df.start_time.dt.year==2019)].head(3)

# after combining 14 observations appear in 2019. let's remove where end_station_id = start_station_id

,trip_id,trip_duration,start_station_id,start_time,start_station_name,end_station_id,end_time,end_station_name,bike_id,user_type,bike_model,trip_duration_calc
38865465,6034741,0.0,7064.0,2019-08-06 07:50:00,51 Parliament St,7100.0,2019-08-06 07:50:00,Dundas St E / Regent Park Blvd,2872.0,Annual Member,NaN,0.0
39250027,6465255,0.0,7417.0,2019-09-04 13:13:00,King St W / Jordan St,7184.0,2019-09-04 13:13:00,Ossington Ave / College St,3550.0,Annual Member,NaN,0.0
39324423,6547689,0.0,7324.0,2019-09-10 21:31:00,King St W / Charlotte St (West),7160.0,2019-09-10 21:31:00,King St W / Tecumseth St,4252.0,Annual Member,NaN,0.0

In [51]:
mask = (df['trip_duration']==0) & (df['start_station_id']==df['end_station_id'])
df = df[~mask]

In [52]:
df[df['trip_duration']==0].start_time.dt.year.value_counts()

start_time
2026    3132
2024    2331
2025     174
2019       5
Name: count, dtype: int64

In [ ]:
# I will proceede with this incomplete data and count the trips even with trip_duration==0, but where start and end station id are different
# my assumtion that there is a problem in data collection process. 
# but i am going to exclude the rows with trip_duration==0 for counting time statistics

In [ ]:
# remove supportinf column 
df.drop(columns=['trip_duration_calc'], inplace=True)

/var/folders/xf/ygl5_zk57kn1rh2h1xj9fyx40000gn/T/ipykernel_92657/800625305.py:2: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop(columns=['trip_duration_calc'], inplace=True)

In [54]:
df.info()

<class 'pandas.DataFrame'>
Index: 44599781 entries, 0 to 44638690
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   trip_id             int64
 1   trip_duration       float64
 2   start_station_id    float32
 3   start_time          datetime64[us]
 4   start_station_name  category
 5   end_station_id      float32
 6   end_time            datetime64[us]
 7   end_station_name    category
 8   bike_id             float32
 9   user_type           category
 10  bike_model          category
dtypes: category(4), datetime64[us](2), float32(3), float64(1), int64(1)
memory usage: 2.4 GB

In [55]:
df.to_parquet('bikeshare_clean.parquet', index=False)